{% set name = "pydy" %}
{% set version = "0.8.0" %}
{% set sha256 = "1b78aa333cbf5b772dcff7384f72ea6324d33156e5cb518c92630b8bdea6ccc7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: pydy-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=44.1.1
    - pip
  run:
    - packaging >=21.3
    - python >={{ python_min }}
    - setuptools >=44.1.1
    - sympy >=1.9
    - numpy >=1.21.5
    - scipy >=1.8.0
    - pywin32-on-windows
  run_constrained:
    # These packages offer enhancements to the code generation and are
    # optional, but if installed in the same environment as PyDy they should
    # meet these requirements. Note that I only include the optional
    # dependencies that are required for "pydy as a library". Once the viz
    # issues are ironed out, we could potentially add Jupyter notebook here.
    - cython >=0.29.28
    - theano >=1.0.5
    - matplotlib >=3.5.1

test:
  requires:
    - python {{ python_min }}
  imports:
    - pydy
    - pydy.codegen
    - pydy.codegen.tests
    - pydy.models
    - pydy.system
    - pydy.utils
    - pydy.viz
    - pydy.viz.tests

about:
  home: http://pydy.org
  license: BSD-3-Clause
  license_file: LICENSE.txt
  license_family: BSD
  summary: Python tool kit for multi-body dynamics.
  doc_url: http://pydy.readthedocs.io
  dev_url: http://github.com/pydy/pydy

extra:
  recipe-maintainers:
    - moorepants
