appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: GF15JBCNO+0UBBf2ZAnW0GzHRDG8Qi54HP7KbPn4eLGaHbmGgJxNvckDZSTg0c92XoCspIcnbf932y0vQcsBh7SwZz8Sko5MXrENgb1sCSH5DdohnYCYFKqThc7PvTkfqO1L3kdj8ICDPnHXj8kpcLoZYDGfgwv6EzjrgeELuUwuRF8GpXYb7LQe2s8zY5glc6PfFzDFKQGk8kNLtDypvR1t+kawDtOqhgBpDarB62BgGLR3/hQX3BhmD20itr57LpJISoKCvt8TJQOeE29LRCR36OBb3VkY38Hbp8UgAVAScklNMmOss6h5imVFCUYFeOuOXTqOcaCkrgCKHRJCIGs948b194p+WmzYoWHr8j4KULZtTjUIKE15/j+yTMFgMKx19esdJ5rAO0jm6vtqQmu+chXSYhFkNmoSp/y14GXOgOlkYj5vHoTy7xeCwUIDL8WeTCxL+ZUwjDeuu7WVqJZvzodgEEmC1QA7hSzFus/5HYIc7EeyHJfFxock88Z2/HRxkU1q0ygxDZP3q+cD1Mmjxi8bzo2zldK7Sh39Fuaz0b7UkJCIL69XL5T8Be5BSisCoITPUS7onUgMHORAjpALvNiy3+S00CG4pWjVdgAqfsJOVenfLQ5iarOuNUqNZpNCt9OdAHFc8tRyIAMAufpq36885Bjtox/seWooKqc=}
provider:
  win: azure
conda_forge_output_validation: true
